#!/usr/bin/env bash
# Scan the production surface while intentionally exempting the tracked agent workspace
# and project documentation.
set -euo pipefail

if ! git rev-parse --show-toplevel >/dev/null 2>&1; then
  echo "provenance-guard: not in a git repository" >&2
  exit 2
fi

forbidden='claude|anthropic|openai|codex|co-authored-by|generated by (an? )?(ai|assistant|model)|ai-generated'
fail=0

is_exempt() {
  case "$1" in
    AGENTS.md|CLAUDE.md|PROGRESS.md|TASKS.md) return 0 ;;
    docs/*|.claude/*|.agent-workspace/*|.githooks/*) return 0 ;;
    scripts/install-git-hooks.sh|scripts/provenance-guard.sh|scripts/remove-agent-workspace.sh|scripts/verify-workspace.sh) return 0 ;;
    *) return 1 ;;
  esac
}

while IFS= read -r -d '' path; do
  is_exempt "$path" && continue
  # Deleted paths have no staged blob.
  if ! git cat-file -e ":$path" 2>/dev/null; then
    continue
  fi
  if git show ":$path" 2>/dev/null | grep -iEq "$forbidden"; then
    echo "PROVENANCE BLOCK: forbidden attribution in staged production file: $path" >&2
    git show ":$path" 2>/dev/null | grep -inE "$forbidden" >&2 || true
    fail=1
  fi
  if printf '%s\n' "$path" | grep -iEq "$forbidden"; then
    echo "PROVENANCE BLOCK: forbidden attribution in production filename: $path" >&2
    fail=1
  fi
done < <(git diff --cached --name-only -z --diff-filter=ACMR)

if [[ "$fail" -ne 0 ]]; then
  exit 1
fi

echo "provenance-guard: ok"
