#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

artifact_list="$tmp/generated-artifacts.txt"
find "$root" \
  \( -path "$root/.git" -o -path "$root/build" -o -path "$root/build-pure" \
     -o -path "$root/build-*" -o -path "$root/cmake-build-*" \
     -o -path "$root/work" -o -path "$root/results" -o -path "$root/tmp" \) -prune \
  -o -type f \
  \( -name '*.rad' -o -name map.rad -o -name '*.gamp' -o -name '*.gam' \
     -o -name '*.xg' -o -name '*.gcsa' -o -name '*.dist' -o -name '*.gbz' \
     -o -name '*.gbwt' -o -name '*.min' \) \
  -print >"$artifact_list"

if [[ -s "$artifact_list" ]]; then
  echo "Generated graph/RAD artifacts found outside ignored work/build directories:" >&2
  sed -n '1,120p' "$artifact_list" >&2
  exit 1
fi
echo "generated artifact scan: ok"

guard_repo="$tmp/guard-repo"
mkdir -p "$guard_repo"
(
  cd "$root"
  tar \
    --exclude='.git' \
    --exclude='build' \
    --exclude='build-pure' \
    --exclude='build-*' \
    --exclude='cmake-build-*' \
    --exclude='work' \
    --exclude='results' \
    --exclude='tmp' \
    -cf - .
) | (
  cd "$guard_repo"
  tar -xf -
)

git -C "$guard_repo" init -q
git -C "$guard_repo" config user.name "Workspace Test"
git -C "$guard_repo" config user.email "workspace@example.invalid"
git -C "$guard_repo" add .
(
  cd "$guard_repo"
  ./scripts/provenance-guard.sh >/dev/null
)
echo "provenance guard clean tracked workspace: ok"

mkdir -p "$guard_repo/src"
printf '%s\n' '// Generated by AI' 'int main() { return 0; }' > "$guard_repo/src/violation.cpp"
git -C "$guard_repo" add src/violation.cpp
if (
  cd "$guard_repo"
  ./scripts/provenance-guard.sh >/dev/null 2>&1
); then
  echo "Expected provenance guard to reject production attribution" >&2
  exit 1
fi
echo "provenance guard violation block: ok"

git -C "$guard_repo" reset -q HEAD -- src/violation.cpp 2>/dev/null || true
rm -f "$guard_repo/src/violation.cpp"
rmdir "$guard_repo/src" 2>/dev/null || true

printf '%s\n' 'Claude and Codex workspace note.' > "$guard_repo/docs/allowed-agent-note.md"
git -C "$guard_repo" add docs/allowed-agent-note.md
(
  cd "$guard_repo"
  ./scripts/provenance-guard.sh >/dev/null
)
echo "provenance guard documentation exemption: ok"

printf '%s\n' 'Document transcript compatibility contract' > "$tmp/good-message"
"$guard_repo/.githooks/commit-msg" "$tmp/good-message"
printf '%s\n' 'Generated by AI' > "$tmp/bad-message"
if "$guard_repo/.githooks/commit-msg" "$tmp/bad-message" >/dev/null 2>&1; then
  echo "Expected commit-message guard to reject attribution" >&2
  exit 1
fi
echo "commit message guard: ok"

echo "verify-workspace: all checks passed"
